/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DropOverlay: typeof import('./src/components/DropOverlay.vue')['default']
    DropZone: typeof import('./src/components/DropZone.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FooterControl: typeof import('./src/components/FooterControl.vue')['default']
    ImageList: typeof import('./src/components/ImageList.vue')['default']
    ListContainer: typeof import('./src/components/ListContainer.vue')['default']
    ListHeader: typeof import('./src/components/ListHeader.vue')['default']
    ListStatus: typeof import('./src/components/ListStatus.vue')['default']
    LoadingDialog: typeof import('./src/components/LoadingDialog.vue')['default']
    ProcessingDialog: typeof import('./src/components/ProcessingDialog.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}
