/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElNotification: typeof import('element-plus/es')['ElNotification']
  const computed: typeof import('vue')['computed']
  const onMounted: typeof import('vue')['onMounted']
  const ref: typeof import('vue')['ref']
}
